server:
  port: 8200

logging:
  level:
    org.springframework.security: info
    org.hibernate.sql: info

springdoc:
  show-oauth2-endpoints: true
  model-and-view-allowed: true
  writer-with-default-pretty-printer: true
  default-support-form-data: true


spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${DOLANG_GOOGLE_CLIENT_ID}
            client-secret: ${DOLANG_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - openid
              - profile