server:
  ssl:
    bundle: "dolang-bundle"

logging:
  file:
    path: /var/log
  level:
    live.dolang: info

spring:
  ssl:
    bundle:
      jks:
        dolang-bundle:
          key:
            alias: "1"
          keystore:
            location: ${DOLANG_SSL_KEY_LOCATION}
            password: ${DOLANG_SSL_KEY_PASSWORD}
            type: "PKCS12"
  datasource:
    url: jdbc:mysql://dolang.live:3306/${DOLANG_MYSQL_DATABASE}
    username: ${DOLANG_MYSQL_USER}
    password: ${DOLANG_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
