server:
  port: 8100

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/dolang
    username: user
    password: password
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: password
  data:
    elasticsearch:
      repositories:
        enabled: true
  jpa:
    open-in-view: false
    properties:
      #      hibernate.generate_statistics: true
      hibernate.log_slow_query: 1000
      hibernate.highlight_sql: true
      jakarta.persistence.schema-generation.database.action: none #update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8200
          jwk-set-uri: http://localhost:8200/oauth2/jwks

  data:
    redis:
      host: localhost
      port: 6379
      user-sentence:
        prefix: "userSentence:"
      user:
        prefix: "user:"
      bookmark:
        postfix: ":bookmarks:"
        count:
          postfix: ":bookmarkCount:"

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    live.dolang: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace