server:
  port: 8300
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: matching
  datasource:
    url: jdbc:mysql://localhost:3306/dolang
    username: user
    password: password
  jpa:
    open-in-view: false
    properties:
      #      hibernate.generate_statistics: true
      hibernate.log_slow_query: 1000
      hibernate.highlight_sql: true
      jakarta.persistence.schema-generation.database.action: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8200
          jwk-set-uri: http://localhost:8200/oauth2/jwks

logging:
  level:
    org.springframework.security: debug
    org.springdoc.web.socket: debug
    live.dolang: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


springdoc.api-docs.enabled: true
springdoc.swagger-ui.enabled: true
springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.path: /swagger-ui.html
