server:
  ssl.bundle: "dolang-bundle"

spring:
  datasource:
    url: jdbc:mysql://dolang-mysql:3306/${DOLANG_MYSQL_DATABASE}
    username: ${DOLANG_MYSQL_USER}
    password: ${DOLANG_MYSQL_PASSWORD}
  jpa:
    properties:
      jakarta.persistence.schema-generation.database.action: none
      jakarta.persistence.schema-generation.scripts.action: none
      jakarta.persistence.create-database-schemas: false
  elasticsearch:
    uris: http://dolang-es:9200
    username: elastic
    password: ${DOLANG_ELASTICSEARCH_PASSWORD}
  data:
    redis:
      host: dolang-redis
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://booted-spring-authorization:8200
          jwk-set-uri: http://booted-spring-authorization:8200/oauth2/jwks
  ssl:
    bundle:
      jks:
        dolang-bundle:
          key:
            alias: "1"
          keystore:
            location: ${DOLANG_SSL_KEY_LOCATION}
            password: ${DOLANG_SSL_KEY_PASSWORD}
            type: "PKCS12"

logging:
  file:
    path: /var/log
  level:
    live.dolang: info
    org.hibernate.SQL_SLOW: info
    org.hibernate.SQL: error
    org.hibernate.orm.jdbc.bind: off